name: PR Lint / Test / Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ENVIRONMENT: ci

jobs:
  go-lint:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Go Lint and format
        run: make go-lint

  go-test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Go Unit tests
        run: make go-test

  go-build:
    name: Go Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Go Build
        run: make go-build

  release:
    name: Create Release Tag
    runs-on: ubuntu-latest
    needs: [go-lint, go-test, go-build]
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Get version
        id: version
        run: |
          VERSION=$(make version | grep 'Build Version:' | sed 's/Build Version: v//')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Create tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "v${{ steps.version.outputs.VERSION }}"
          git push origin "v${{ steps.version.outputs.VERSION }}"

